name: Test Runner
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run a script
        run: echo "Hello from self-hosted runner!"