name: Test Runner
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Copy files to htdocs
        run: |
          # Dirígete a la carpeta htdocs donde está el código de tu aplicación
          cd /home/bitnami/htdocs
          # Limpia archivos antiguos si es necesario
          rm -rf *
          # Copia los archivos actualizados desde el repositorio
          cp -r /path/to/your/local/git/repo/* .

      - name: Restart Apache
        run: |
          sudo systemctl restart apache2
        
